spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    database: ${DB}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    generate-ddl: true
    database-platform: ${DB_PLATFORM}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: ${INFOLEARN_DB_URL}
    username: ${INFOLEARN_DB_USERNAME}
    password: ${INFOLEARN_DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

#  data:
#    mongodb:
#      uri:

datasource:
  mongo:
    url: ${MONGO_URL}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessExpiredAt: ${ACCESS_EXP}
  refreshExpiredAt: ${REFRESH_EXP}

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  protocol: ${MAIL_PROTOCOL}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

aws:
  bucketName: ${AWS_BUKET}
  secretKey: ${AWS_SECRET_KEY}
  accessKey: ${AWS_ACCESS_KEY}

springdoc:
  swagger-ui:
    validator-url: false

logging:
  level:
    web: debug

socket:
  port: ${SOCKET_PORT:3000}
  host: ${SOCKET_HOST:127.0.0.1}