package com.example.hierarchical_infolearn.global.file.exception

import com.example.hierarchical_infolearn.global.error.ErrorCode
import com.example.hierarchical_infolearn.global.error.data.GlobalException

object FileShouldBeImageTypeException: GlobalException(ErrorCode.FILE_SHOULD_BE_IMAGE_TYPE)